### ISSUE TITLE
Pause iTunes and Spotify not working

### ISSUE THREAD

**Issue by MaximilianSchwarz** [64characters/Telephone#553] opened 2019-10-13 15:34 UTC
I have the newest Version of Telephone and i checkt the option in settings. But if my phone rings nothing is stoped. Also i accept the phone call the music isn't stoped

**Comment by AndrzejOlender** [comment] 2019-10-16 10:44
It doesn't work for me either.

**Comment by eofster** [comment] 2019-10-16 13:53
Which macOS version are you using? Since 10.14 Mojave, macOS has a special permission for an app to control other app via AppleScript, which is how iTunes pausing works. When it’s used first time, there should be a dialog asking for that permission. I’ve also heard that due to a possible problem in macOS it never appeared for some people.

Please check if you have Telephone section and iTunes checkbox checked in:

System Preferences > Security & Privacy > Privacy > Automation

**Comment by eofster** [comment] 2019-11-05 22:15
To my knowledge, one can’t add it manually, but it is possible to reset this type of consent in the system. As a result, macOS should ask you again first time Apple Events are used in each app. To reset this, run the following command in Terminal:

```
tccutil reset AppleEvents
```

**Comment by eofster** [comment] 2019-11-05 22:19
After this command is executed, the OS should display a prompt _“Telephone” wants to control “iTunes”_ next time a call is answered while iTunes is playing.

**Comment by eofster** [comment] 2019-11-14 18:06
@MaximilianSchwarz where you able to try the command above and if yers, did help?

**Comment by eofster** [comment] 2019-12-10 17:47
I guess the problem is that that on Catalina iTunes has been replaced with Music app, which is completely different app from the OS’ standpoint. So it requires the same support as for iTunes and Spotify.

**Closed** 2019-12-20 19:19 UTC
Labels: bug
