### ISSUE TITLE
Volume getting increased to 100% when making a call

### ISSUE THREAD

**Issue by luckman212** [64characters/Telephone#568] opened 2020-03-22 21:10 UTC
For some reason, when making a call (either manually or via sip: URI) my system's Output Volume gets increased to 100%.  This causes a blast from my speakers or headphones. When using AirPods, the volume doesn't seem to go to 100%, but it does get increased by some seemlingly arbitrary amount. Not sure if this is a bug or some intentional behavior? Can it be fixed/disabled?

- macOS 10.15.3 (19D76)
- Telephone 1.4.1 (133)

**Comment by eofster** [comment] 2020-03-22 21:14
You’re using a Mac Book 2016 or later, right? People on these devices reported this problem, but unfortunately, I couldn’t reproduce it so far.

**Comment by luckman212** [comment] 2020-03-22 22:53
I'm using a Mac Mini 2018 model.

**Comment by luckman212** [comment] 2020-05-21 19:16
Saw this in the release notes for 1.4.6

> _Fixed a problem where output volume could change at the beginning of a call._

Seems like that's means this one is fixed? 🤞

**Comment by eofster** [comment] 2020-05-21 22:20
Yes, by #597. Has it been fixed for you? Turns out, it was remembering the volume at the beginning of the first call after the app start and then resetting it on the following calls. And it was happening only on some Mac models.

**Comment by luckman212** [comment] 2020-05-22 02:28
Nice! 👍 I'm away from the Mac that had this issue but I'll check tomorrow and report back. Fix looks promising though.

**Comment by luckman212** [comment] 2020-05-22 15:29
@eofster So far so good - did some testing this morning and can't reproduce this anymore! Thank you.

**Comment by eofster** [comment] 2020-05-22 22:58
Great, thanks for letting me know. Closing the issue, but feel free to reopen it if you see the problem again.

Fixed by #598

**Closed by eofster** 2020-05-22 22:58 UTC
